// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1X33mMM1BDnFetoI17fzxU8hhSsX7t8k',
    appId: '1:1085802258375:web:c343ecbb473702310c03e2',
    messagingSenderId: '1085802258375',
    projectId: 'elapse',
    authDomain: 'elapse.firebaseapp.com',
    storageBucket: 'elapse.appspot.com',
    measurementId: 'G-CZP240Y9ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRS0lYO4_ljPK5G9KJcYdo-33FRUNjec',
    appId: '1:1085802258375:android:a445f127ec8ae9650c03e2',
    messagingSenderId: '1085802258375',
    projectId: 'elapse',
    storageBucket: 'elapse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9NIyftybAfImb8wteA0s1UV0t_gqZgB4',
    appId: '1:1085802258375:ios:ca34fc646b6a50bf0c03e2',
    messagingSenderId: '1085802258375',
    projectId: 'elapse',
    storageBucket: 'elapse.appspot.com',
    iosClientId: '1085802258375-f1vau2e0ddrdtti51ublrs33jrgnhv23.apps.googleusercontent.com',
    iosBundleId: 'com.example.elapseApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9NIyftybAfImb8wteA0s1UV0t_gqZgB4',
    appId: '1:1085802258375:ios:ad62a372ff6464ea0c03e2',
    messagingSenderId: '1085802258375',
    projectId: 'elapse',
    storageBucket: 'elapse.appspot.com',
    iosClientId: '1085802258375-vmdr3i7hneb8a3lvenlgvdq8ae9vi1kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.elapseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1X33mMM1BDnFetoI17fzxU8hhSsX7t8k',
    appId: '1:1085802258375:web:12a6e56feecf5b6e0c03e2',
    messagingSenderId: '1085802258375',
    projectId: 'elapse',
    authDomain: 'elapse.firebaseapp.com',
    storageBucket: 'elapse.appspot.com',
    measurementId: 'G-2V9D8WQ6K6',
  );

}